services:
  - docker

language: generic

before_install:
  - docker build -t jj807/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jj807/docker-react npm run test -- --coverage

after_script:
  - exit 0

after_success:
  - echo "hurray!"
