services:
  - docker

before_install:
  - docker build -t jj807/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true jj807/docker-react npm run test -- --coverage

language: minimal
deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket-name: "elasticbeanstalk-us-east-1-403548837988"
  bucket-path: "docker-react"
  on:
    branch: master
  access_key_id: "$AWS_ACCESS_KEY"
  secret_access_key:
    secure: "$AWS_SECRET_KEY"